apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adreq-staging

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/songfei1983/adreq
    newTag: latest
